export const PROJECTS = [
  {
    id: "connections",
    title: "Connections",
    description: "Co-Founded and built an event management and community-building platform aimed to help people monetize their skills.",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80",
    tags: ["JS", "Cloud Servers", "APIs"],
    link: "https://www.connectionsforcommunity.org",
    highlight: true,
  },
  {
    id: "engine",
    title: "3D Simulation Engine",
    description: "Built a custom knock-off matlab with movement mechanics all in Java.",
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80",
    tags: ["Java"],
    link: "#",
    highlight: true,
  },
  {
    id: "neural-interface-system",
    title: "Neural Interface System",
    description: "A brain-computer interface that translates neural signals into digital commands. Built with real-time signal processing and machine learning algorithms.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80",
    tags: ["Python", "TensorFlow", "Signal Processing"],
    link: "#",
  },
  {
    id: "autonomous-drone-fleet",
    title: "Autonomous Drone Fleet",
    description: "Coordinated multi-drone system for search and rescue operations. Features swarm intelligence and real-time obstacle avoidance.",
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&auto=format&fit=crop&q=80",
    tags: ["ROS", "C++", "Computer Vision"],
    link: "#",
  },
  {
    id: "robotic-exoskeleton",
    title: "Robotic Exoskeleton",
    description: "Assistive wearable device for mobility enhancement. Incorporates adaptive control systems and haptic feedback mechanisms.",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80",
    tags: ["Embedded Systems", "CAD", "Arduino"],
    link: "#",
  },
  {
    id: "smart-manufacturing-cell",
    title: "Smart Manufacturing Cell",
    description: "Industry 4.0 compliant automated production line with predictive maintenance and quality control systems.",
    image: "https://images.unsplash.com/photo-1565514020179-026b92b2cc7b?w=800&auto=format&fit=crop&q=80",
    tags: ["PLC", "SCADA", "IoT"],
    link: "#",
  },
  {
    id: "surgical-robot-assistant",
    title: "Surgical Robot Assistant",
    description: "Precision surgical system with 6-DOF manipulator arm. Enables minimally invasive procedures with sub-millimeter accuracy.",
    image: "https://images.unsplash.com/photo-1559757175-7b21671c7d36?w=800&auto=format&fit=crop&q=80",
    tags: ["Medical Devices", "MATLAB", "Control Systems"],
    link: "#",
  },
];
